# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS_Kimjiwook' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOS_Kimjiwook
  pod 'AFNetworking', '~> 3.0'
  pod 'HTMLReader'
end
